# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
# Simple/example things
  - trigger: ":hi"
    replace: "Hi there!"

# Terminal commands

  # Dates
  - trigger: ":date"
    replace: "{{termdate}}"
    vars:
        - name: termdate
          type: shell
          params:
              cmd: "/fast_files/git_repos/custum_scripts/date_script"

  # Current terminal
  - trigger: ":term"
    replace: "{{terminal}}"
    vars:
        - name: terminal
          type: shell
          params:
              cmd: "cat /fast_files/git_repos/custum_scripts/terminal | grep -v '^#' | tr -d '\n'"

# Personal emoji shortcuts
  - trigger: ":p:"
    replace: "😛"

  - trigger: ":pedoface:"
    replace: "😏"

# End of mail signature in both English and Dutch
  - trigger: ":end_of_mail_en"
    replace: "Kind regards,\nJan-Pieter Baert"

  - trigger: ":end_of_mail_nl"
    replace: "Met vriendelijk groeten,\nJan-Pieter Baert"
