#!/bin/bash

title=$(playerctl metadata title 2>/dev/null|| echo "")
artist=$(playerctl metadata artist 2>/dev/null || echo "")
playPauze=$(playerctl status 2>/dev/null || echo "")
playerName=$(playerctl --list-all | head -n1)

retVal=""

if [ "$(playerctl metadata 2>/dev/null | grep -i coldplay)" ]
then
	playerctl next
	notify-send "I skipped it, fuck coldplay"
fi

if [ "$artist" ]
then
	retVal+="${artist}: "
fi

if [ "$title" ]
then
	retVal+="${title}"
fi

if [ "$(echo $playPauze | grep Play)" ]
then
	retVal+=" ▶"
fi

#if [ "$(echo $playPauze | grep Pause)" ]
#then
#	retVal+=" ⏸"
#fi

if [ "$(echo $playerName | grep -vy "No players")" ]
then
  retVal+=" ($playerName)"
fi

if [ "$retVal" ]
then
	echo $retVal
else
	echo "No playerctl playing"
fi


case $BLOCK_BUTTON in
  1) playerctl play-pause ;;
  4) playerctl play ;; # scroll up, increase
  5) playerctl pause ;; # scroll down, decrease
esac
